#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# Phase 4 · Containers
#
# Writes .env for docker compose (no passwords in there — only the JWT
# secret, ports and profile selection), pulls images and starts the stack.
# ──────────────────────────────────────────────────────────────────

[[ -z "${CLEZJELLY_COMMON_LOADED:-}" ]] && source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
[[ -z "${CLEZJELLY_API_LOADED:-}" ]]    && source "$(dirname "${BASH_SOURCE[0]}")/../lib/api.sh"

env_write() {
  components_derive
  local jwt tz
  # Fresh from credentials, or carried over from the existing .env (so up/down/update need no passphrase)
  jwt="${ALTMOUNT_JWT_SECRET:-$(env_get "$CLEZJELLY_ROOT/.env" ALTMOUNT_JWT_SECRET || true)}"
  if [[ -z "$jwt" ]]; then
    log_err "No JWT secret yet — run the install first (./install.sh install)."
    return 1
  fi
  # Time zone: honour $TZ, else the Mac's own setting, else Vienna
  tz="${TZ:-$(readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||')}"
  tz="${tz:-Europe/Vienna}"
  cat > "$CLEZJELLY_ROOT/.env" <<EOF
# Generated by install.sh — rebuilt on every run, don't edit by hand.
TZ=${tz}
PUID=$(id -u)
PGID=$(id -g)
ALTMOUNT_JWT_SECRET=${jwt}
COMPOSE_PROFILES=${COMPOSE_PROFILES}
SEERR_BIND=${SEERR_BIND}
ALTMOUNT_BIND=${ALTMOUNT_BIND}
EOF
  chmod 600 "$CLEZJELLY_ROOT/.env"
}

# Stop and remove optional services that were switched off
_remove_disabled_services() {
  local svc enabled
  for svc in seerr bazarr; do
    if [[ "$svc" == "seerr" ]]; then enabled="$ENABLE_SEERR"; else enabled="$ENABLE_BAZARR"; fi
    if [[ "$enabled" != "true" ]]; then
      COMPOSE_PROFILES="$svc" docker compose rm -sf "$svc" >>"$UI_LOG" 2>&1 || true
    fi
  done
}

containers_start() {
  ui_phase 4 5 "Containers"
  cd "$CLEZJELLY_ROOT" || return 1

  env_write || return 1
  log_ok ".env written (profiles: ${COMPOSE_PROFILES:-core only})"

  ui_spin "Pulling images" docker compose pull || return 1
  ui_spin "Starting the stack" docker compose up -d --remove-orphans || return 1
  _remove_disabled_services

  log_step "Waiting for services"
  if ! ui_wait "AltMount" "http://localhost:8080" 150; then
    log_err "AltMount did not start. Last log lines:"
    docker compose logs --tail 15 altmount 2>&1 | sed 's/^/      /' | tee -a "$UI_LOG" || true
    log_info "Fix the cause, then run: ./install.sh relink"
    return 1
  fi
  ui_wait "Prowlarr" "http://localhost:9696/ping"      150 || true
  ui_wait "Radarr"   "http://localhost:7878/ping"      150 || true
  ui_wait "Sonarr"   "http://localhost:8989/ping"      150 || true
  if [[ "$ENABLE_SEERR" == "true" ]];  then ui_wait "Seerr"  "http://localhost:5055/api/v1/status" 150 || true; fi
  if [[ "$ENABLE_BAZARR" == "true" ]]; then ui_wait "Bazarr" "http://localhost:6767"               150 || true; fi
}

# Quick actions used by the menu / CLI
stack_up() {
  cd "$CLEZJELLY_ROOT" || return 1
  components_load
  env_write || return 1
  ui_spin "Starting the stack" docker compose up -d --remove-orphans || return 1
  _remove_disabled_services
  if [[ "$OPEN_JELLYFIN" == "true" && -d "/Applications/Jellyfin.app" ]]; then
    open -a Jellyfin 2>/dev/null && log_ok "Jellyfin launched"
  fi
}

stack_down() {
  cd "$CLEZJELLY_ROOT" || return 1
  ui_spin "Stopping the stack" docker compose down || return 1
  log_info "Jellyfin.app keeps running — quit it with Cmd+Q if you like."
}

stack_update() {
  cd "$CLEZJELLY_ROOT" || return 1
  components_load
  env_write || return 1
  ui_spin "Pulling newer images" docker compose pull || return 1
  ui_spin "Recreating changed containers" docker compose up -d --remove-orphans || return 1
  ui_spin "Pruning old images" docker image prune -f || true
}
